services:
  - type: web
    name: ogdash
    env: node
    buildCommand: npm install && cd NOVO && npm install && cd NOVO && node scripts/setup.js || true
    startCommand: cd NOVO && npm install && node scripts/setup.js || true && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: ogdash
          property: port

