name: Rodar Pipeline Ouvidoria

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * *"   # 13:00 UTC (10:00 BRT)
    - cron: "0 21 * * *"  # 21:00 UTC (15:00 BRT)
jobs:
  rodar_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          # --- ESTA É A LINHA CORRETA PARA A SUA ESTRUTURA DE PASTAS ---
          pip install -r .github/workflows/requirements.txt

      - name: Criar arquivo de credenciais
        run: |
          echo "${{ secrets.GDRIVE_CRED_JSON_BASE64 }}" | tr -d '\n\r\t ' > .github/workflows/credentials.json
          
          echo "--- INÍCIO DO ARQUIVO credentials.json (Base64 RAW em HEX que o Python lê) ---"
          cat .github/workflows/credentials.json | xxd -p
          echo "\n--- FIM DO ARQUIVO credentials.json (Base64 RAW em HEX que o Python lê) ---"

      - name: Rodar script Python
        run: python .github/workflows/main.py
